# Generated by Django 4.2.26 on 2026-02-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="budget",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
